---
title: "Create initial distribution"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{init_dist}
  %\VignetteEngine{knitr::knitr}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Work in progress, currently only used to hold the R code without shipping the 
package with R scripts.

```{r setup}
library(MoDVE)
```


```{r create_init_dist, eval=FALSE}

distr_params <- parse_config("tests/config_a3.toml")
set.seed(distr_params$seed, kind="Mersenne-Twister")

# Prepare folder paths
DirectoryModelMain <- distr_params$DirectoryModelMain
dir_microhab <- distr_params$DirectoryMicrohabitatMain
DirectorySpeciesPoolsMain <- distr_params$DirectorySpeciesPools

dir.create(DirectoryModelMain, recursive=TRUE)

# Load microhabitat matrix
microhabitat_filename <- paste("MicrohabitatMatrix", distr_params$TimeStep, ".rds", sep="")
path_to_microhab <- file.path(dir_microhab, microhabitat_filename)
microhab_mat <- readRDS(path_to_microhab)
# Transform light values from relative to absolute
microhab_mat[, , , 3] <- microhab_mat[, , , 3] * distr_params$Imax

for (numPool in distr_params$numSpeciesPools[1]:distr_params$numSpeciesPools[2]) {

  #numPool <- 4
  #numReplicates <- 1

  # Load the species pool
  species_filename <- paste("SpeciesPool", numPool, ".csv", sep = "")
  Input_file <- file.path(DirectorySpeciesPoolsMain, species_filename)
  species_df <- read.csv(Input_file)

  for (numReplicates in seq_len(distr_params$replicatePerSpeciesPool)) {

    path_to_output <- file.path(DirectoryModelMain, paste(
      "ID_SpeciesP_", numPool, "_Rep_", numReplicates, ".csv", sep = ""
    ))

    largest_inds_first <- TRUE
    largest_voxels_first <- TRUE

    # Generate the distribution and individual traits
    draw_initial_individuals(
      distr_params, species_df, microhab_mat, path_to_output,
      largest_inds_first = distr_params$SingleSpeciesModel,
      largest_voxels_first = distr_params$MethodVoxel
    )
  }
}

```
