---
title: "Create species pool"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{species_pool}
  %\VignetteEngine{knitr::knitr}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Work in progress, currently only used to hold the R code without shipping the 
package with R scripts.

```{r setup}
library(MoDVE)
```


```{r create_sp_pool, eval=FALSE}

species_params <- parse_config("tests/config_a2.toml")
check_species_params(species_params)

# Prepare output table
SaveDirectory <- file.path(species_params$MainOutputDirectory)
dir.create(SaveDirectory, recursive=TRUE)
trait_names <- c("SpeciesID", species_trait_names())
sp_traits_df <- data.frame(matrix(ncol = length(trait_names), nrow = 0))
colnames(sp_traits_df) <- trait_names

set.seed(species_params$seed, kind="Mersenne-Twister")  # integer for fixed seed or NULL for random

for (pool_nb in 1:species_params$numSpeciesPools) {
  for (sp in 1:species_params$NumberOfSpecies) {

    species_traits <- c("SpeciesID" = sp, draw_species_traits(species_params))
    sp_traits_df[sp, ] <- as.data.frame(species_traits)
  }

  # Save trait dataframe
  SpeciesPoolFileName <- paste("SpeciesPool", pool_nb, ".csv", sep = "")
  write.csv(sp_traits_df, file.path(SaveDirectory, SpeciesPoolFileName),
            row.names = FALSE)
}

```
