// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calc_light_matrix
NumericVector calc_light_matrix(const DataFrame& vox_dt, const List& config);
RcppExport SEXP _MoDVE_calc_light_matrix(SEXP vox_dtSEXP, SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type vox_dt(vox_dtSEXP);
    Rcpp::traits::input_parameter< const List& >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_light_matrix(vox_dt, config));
    return rcpp_result_gen;
END_RCPP
}
// find_intersecting_voxels
List find_intersecting_voxels(NumericVector coords_begin, NumericVector coords_end);
RcppExport SEXP _MoDVE_find_intersecting_voxels(SEXP coords_beginSEXP, SEXP coords_endSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type coords_begin(coords_beginSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type coords_end(coords_endSEXP);
    rcpp_result_gen = Rcpp::wrap(find_intersecting_voxels(coords_begin, coords_end));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MoDVE_calc_light_matrix", (DL_FUNC) &_MoDVE_calc_light_matrix, 2},
    {"_MoDVE_find_intersecting_voxels", (DL_FUNC) &_MoDVE_find_intersecting_voxels, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_MoDVE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
