#' Get the sequential index of a coordinate in a 3D matrix
#'
#' Convert an XYZ position into the sequential position (i.e., ranging between
#' 1 and dimX x dimY x dimZ) inside the matrix
#'
#' @param x x-coordinate
#' @param y y-coordinate
#' @param z z-coordinate
#' @param dimX X-dimension of the matrix
#' @param dimY Y-dimension of the matrix
#'
index_3d <- function(x, y, z, dimX, dimY) {
  return(x + dimX * (y - 1) + dimX * dimY * (z - 1))
}

#' Convert a sequential index in a 3D matrix into X, Y and Z coordinates
#' @param i index ranging from 1 to the size of the matrix
#' @param dimX X-dimension of the matrix
#' @param dimY Y-dimension of the matrix
#'
index_to_3d_coords <- function(i, dimX, dimY) {
  return(c(
    "x" = (i - 1) %% dimX + 1, # x
    "y" = (i - 1) %/% dimX %% dimY + 1, # y
    "z" = (i - 1) %/% (dimX * dimY) + 1 # z
  ))
}

#' Generate a data frame containing species traits
#'
#' Convenience wrapper that calls [draw_species_traits()] for multiple species
#' and formats the output as a dataframe.
#'
#' @param nb_species how many species should be sampled?
#' @param species_params a list containing named elements and with values for
#' the parameters of [draw_species_traits()], e.g. as generated by
#' [draw_rnd_species_params()].
#'
#' @return a `data.frame` with `nb_species` rows and columns containing random
#' values for all species traits required to run a MoDVE simulation.
#'
create_rnd_species_df <- function(nb_species, species_params = draw_rnd_species_params()) {

  species_df <- purrr::imap_dfr(1:nb_species, function(x, i) {
    as.data.frame(c("SpeciesID" = i, draw_species_traits(species_params)))
  })

  return(species_df)
}

#' Shorthand function for generating species traits hyperparameters
#'
#' Generates a list containing all parameters required to run
#' [draw_species_traits()] with random but legal values.
#'
#' @param max_val sets the maximum value to sample hyperparameters that otherwise
#' don't have a theoretical maximum value (the minimum is zero).
#'
#' @export
draw_rnd_species_params <- function(max_val = 100) {

  sp_params <- list(
    MaxMassLogScaleRandom = stats::runif(1) > 0.5, # coin flip
    MaxMassRandom = stats::runif(1, 0, max_val),
    InterceptAgeMaturity = stats::runif(1, 0, max_val),
    AgeAtMaturityDevCorr = stats::runif(1, 0, 1),
    ScalingAgeMaturity = stats::runif(1, 0, 1),
    MassAtMaturityRelativeRandom = stats::runif(1, 0, 1),

    CorrelationMassRecruitment = stats::runif(1) > 0.5,

    DispersalKernelRandom = stats::runif(1, 0, max_val),
    DispersalKernelAsymmetryRandom = stats::runif(1, 0, 1),

    HeightBreadthRandom = stats::runif(1, 0, 1),

    Imax = stats::runif(1, 0, max_val),
    kL = stats::runif(1, 0, 1),
    LAI = stats::runif(1, 0, min(10, max_val))
  )

  sp_params$MaxMassRandom[2] <- draw_max_value(sp_params$MaxMassRandom[1], max_val)
  sp_params$MassAtMaturityRelativeRandom[2] <- draw_max_value(
    sp_params$MassAtMaturityRelativeRandom[1], 1
  )
  sp_params$DispersalKernelRandom[2] <- draw_max_value(sp_params$DispersalKernelRandom[1], max_val)
  sp_params$DispersalKernelAsymmetryRandom[2] <- draw_max_value(
    sp_params$DispersalKernelAsymmetryRandom[1], 1
  )
  sp_params$HeightBreadthRandom[2] <- draw_max_value(sp_params$HeightBreadthRandom[1], 1)

  # Parameters that depend on the correlation mass option
  if (sp_params$CorrelationMassRecruitment) {
    sp_params$RecruitmentInvestmentRelDevCorr <- stats::runif(1, 0, 1)
    sp_params$RecruitmentInvestmentRelMeanCorr <- stats::runif(1, 0, 1)
  }
  else {
    sp_params$RecruitmentIncRandom <- stats::runif(1, 0, 1)
    sp_params$RecruitmentIncRandom[2] <- draw_max_value(sp_params$RecruitmentIncRandom[1], 1)

    sp_params$RecruitmentInvestmentRelMeanRandom <- stats::runif(1, 0, 1)
    sp_params$RecruitmentInvestmentRelMeanRandom[2] <- draw_max_value(sp_params$RecruitmentInvestmentRelMeanRandom[1], 1)
  }
  return(sp_params)
}

#' Draw max value for uniform parameters
#'
#' Given the minimum value and an upper bound, draw a random max value such that
#' the max value is larger than the min and smaller than the upper bound
#'
#' @param min_val the minimum value of the uniform distribution
#' @param upper_bound upper bound to not exceed when drawing the value
#'
draw_max_value <- function(min_val, upper_bound) {
  return(min_val + stats::runif(1, 0, upper_bound - min_val))
}

#' Draw random values for individual initialisation parameters
#'
#' Returns a list with random values for [draw_initial_individuals()] argument
#' `distr_params`
#'
#' @return a list with four elements: `SurfaceBiomassScaling`,
#' `IndividualsPerSpecies`, `ScalingPerHa`, and `PercentageMaturePerSpecies`
#'
draw_rnd_initial_inds_params <- function() {
  return(list(
    "SurfaceBiomassScaling" = stats::runif(1, 1e-7, 10),
    "IndividualsPerSpecies" = sample(1:100, 1),
    "ScalingPerHa" = FALSE,
    "PercentageMaturePerSpecies" = stats::runif(1, 0, 100)
  ))
}

#' Create a microhabitat matrix of specified dimensions and fill its
#' surface area and light layer based on species requirements
#'
#' Microhabitat is set to be suitable for the *first* species in SpeciesPool,
#' and may not be suitable for other species.
#'
#' Surface area is set such that:
#' * a random fraction of all voxels are suitable
#' * each suitable voxels can sustain between 1 and 10 individuals of maximum
#' mass
#'
#' Surface area loss is set to zero.
#'
#' Light is set as the `OptimumLight` trait of the first species.
#'
#' @param SpeciesPool a `data.frame` containing one row per species and at least
#' two columns for species traits `MaximumMass` and `OptimumLight`.
#' @param dimensions a 3-element vector containing the X, Y and Z dimensions of
#' the matrix.
#' @param SurfaceBiomassScaling a strictly positive parameter scaling the surface
#'  area requirement as a function of the mass of the individual:
#' \deqn{S = M^{2/3} / g_S}.
#'
#' @return a 4D array where the first three dimensions are the microhabitat
#' dimensions and the last dimensions contains 3 layers: surface area, surface
#' area loss (not set), and light conditions.
#'
create_rnd_microhabitat <- function(SpeciesPool, dimensions, SurfaceBiomassScaling) {

  Microhabitat <- array(0, c(dimensions, 3))
  nb_suitable_voxels <- round(prod(dimensions) * stats::runif(1, 0, 1))
  suitable_voxels <- sample(1:prod(dimensions), nb_suitable_voxels)
  reqd_sa_per_ind <- SpeciesPool$MaximumMass[1]^(2/3) / SurfaceBiomassScaling
  surface_area_mat <- array(0, dim = dimensions)
  surface_area_mat[suitable_voxels] <- reqd_sa_per_ind *
    sample(1:10, length(suitable_voxels), replace = TRUE)
  Microhabitat[, , , 1] <- surface_area_mat
  Microhabitat[, , , 3] <- SpeciesPool$OptimumLight[1]

  return(Microhabitat)
}
